services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    volumes:
      - db-data:/var/lib/mysql

  nextcloud:
    image: nextcloud:32-apache
    ports:
      - "8088:80"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
    volumes:
      - nextcloud-data:/var/www/html
      - .:/var/www/html/custom_apps/drawio
    depends_on:
      - db

volumes:
  db-data:
  nextcloud-data:
